### PR TITLE
Add test for unsubscribing from resources

### PR DESCRIPTION
**Pull request by BobyMCbobs**

### CODE REVIEW

**Review by zachmandeville — CHANGES_REQUESTED** [review]
This is a great start, and the test passes which is awesome.  Well done for this!  I think the test can be improved before a merge though.  Specifically for it to move from imperative steps to declarative steps.

The main issue is in the given statements.  The two `And`'s contain actions and should just be a declaration of state. 

High level, the test could be written as:
```
Given I am subscribed to multiple clusters from a server
When i send a new request for a single resource
Then I should get a response with only that resource
```

To have it be written in our yaml style, it could be condensed to 4 steps:
```
Given a target setup with snapshot matching yaml...
And an established subscription that was initiated with request matching yaml...
When i send a new request matching yaml...
Then i get a response matching yaml...
```

I am not happiest with my wording of the second step, but that is the general gist.  What do you think?

**Comment by BobyMCbobs** [comment]
> This is a great start, and the test passes which is awesome. Well done for this! I think the test can be improved before a merge though. Specifically for it to move from imperative steps to declarative steps.

Thank you!
Good to see that the implementation is there.

I think that declarative steps would definitely be more ideal.

> The main issue is in the given statements. The two `And`'s contain actions and should just be a declaration of state.
> 
> High level, the test could be written as:
> 
> ```
> Given I am subscribed to multiple clusters from a server
> When i send a new request for a single resource
> Then I should get a response with only that resource
> ```
> 
> To have it be written in our yaml style, it could be condensed to 4 steps:
> 
> ```
> Given a target setup with snapshot matching yaml...
> And an established subscription that was initiated with request matching yaml...
> When i send a new request matching yaml...
> Then i get a response matching yaml...
> ```
> 
> I am not happiest with my wording of the second step, but that is the general gist. What do you think?

This sounds good. I'll see what I can do :raised_hands:

**Comment by BobyMCbobs** [comment]
I've updated the test in 0502c15, as per what I the previous message

I think I'm ready for review :smile: 

cc @zachmandeville

**Comment by zachmandeville** [comment]
thank you for this, @BobyMCbobs

**Comment by BobyMCbobs** [comment]
Woohoo!
Thanks for the merge :raised_hands:

**Pull request merged**
